In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('menu.csv')

In [6]:
df.head(2)

,ename,gmail,github,domain,vercel,role,2025-01-07,2025-01-08,2025-01-09,2025-01-10,...,2025-01-16,2025-01-17,2025-01-20,2025-01-21,2025-01-22,2025-01-23,2025-01-24,2025-02-03,2025-02-04,2025-02-05
0,TOM,tom@diginori.com,ppabam,sunsin.shop,https://sunsin.vercel.app,PM,순대국,비지찌개,"냉동김밥,컵라면",잔치국수,...,오징어 덮밥,짜장면,집밥 도시락,소고기무국,-,오징어덮밥,볶음밥,짜장면,-,-
1,cho,j01040864205@gmail.com,cho6019,cho6019.store,https://cho6019.vercel.app,행동강령 수립 위원회,닭개장,규동,얼큰 순대국밥,스파게티,...,간짜장,스파게티,버섯 비프 카레,스파게티,설렁탕,치킨마요덮밥,등심돈까스,"치즈라면, 김밥",-,-

In [4]:
df_melt = df.drop(columns=['gmail', 'github', 'domain', 'vercel', 'role'])

In [14]:
df_melt.head(10)

,ename,2025-01-07,2025-01-08,2025-01-09,2025-01-10,2025-01-13,2025-01-14,2025-01-15,2025-01-16,2025-01-17,2025-01-20,2025-01-21,2025-01-22,2025-01-23,2025-01-24,2025-02-03,2025-02-04,2025-02-05
0,TOM,순대국,비지찌개,"냉동김밥,컵라면",잔치국수,제육덮밥,소고기무국,소고기덮밥,오징어 덮밥,짜장면,집밥 도시락,소고기무국,-,오징어덮밥,볶음밥,짜장면,-,-
1,cho,닭개장,규동,얼큰 순대국밥,스파게티,한솥,순대국밥 고기만,파스타,간짜장,스파게티,버섯 비프 카레,스파게티,설렁탕,치킨마요덮밥,등심돈까스,"치즈라면, 김밥",-,-
2,hyun,"닭개장(특) , 꽈배기",주먹밥,얼큰 순대국밥,불닭로제찜닭,한솥,순대국밥,까르보나라 파스타,간짜장 곱빼기,"참치김밥,라볶이",Forrk 카레,"고등어구이,제육볶음",육회비빔밥,김치찌개,안심까스,라돈 모다기,-,-
3,JERRY,닭개장,주먹밥,얼큰 순대국밥,불닭로제찜닭,한솥,뼈해장국,모짜렐라 토마토 파스타,짬짜면,<결석>,함바그 카레,"고등어구이,제육볶음",설렁탕,"치킨마요,찹쌀탕수육",반반가츠,모다기,-,-
4,SEO,볶음밥,유부초밥,볶음밥,"볶음밥 , 연어",연어덮밥,볶음밥,연어덮밥,샌드위치,유부초밥,유부초밥,"고등어구이,제육볶음",불고기,닭다리살 간장조림,-,닭죽,-,-
5,jiwon,닭개장,스키야키,"참깨라면 작은컵,삼각김밥",불닭로제찜닭,-,-,-,짬짜면,떡라면,카레,쉐이크,"쉐이크 , 샌드위치",한솥,부리또,잔치국수,-,-
6,jacob,자장면,텐동,얼큰 설렁탕,부대찌개,참치김치찌개,한솥,햄 김치찌개,"비빔,잔치 국수 반반",안심 돈카츠,백반,얼큰미나리 샤브세트,순두부 찌개,육회비빔밥,순두부찌개,김치 찌개,-,-
7,heejin,덮밥,덮밥,설렁탕,부대찌개,김밥,김밥,오므라이스,돈까스,"볶음밥 , 컵라면",볶음밥,얼큰미나리 샤브세트,오므라이스,김밥,김치찌개,샌드위치,-,-
8,lucas,볶음밥,규동,한우 곰탕,부대찌개,꽃게 된장찌개,한솥,"생고기김치찌개,라면사리","비빔국수 , 반 계란 김밥",안심 돈카츠,낙지 볶음,얼큰미나리 샤브세트,햄 김치찌개,육회비빔밥,콩나물해장국,제육볶음,-,-
9,nuni,일반 짬뽕 보통,무공 옛날돈가스,얼큰 설렁탕,부대찌개,"고기김치찌개,라면세트",한솥,순두부찌개,반반국수(비빔&잔치),카레 돈카츠 세트,제육볶음,x,순두부 찌개,육회비빔밥,"김치찌개,라면",제육볶음,-,-

In [5]:
df_melt = df_melt.melt(id_vars=['ename'], var_name='dt', value_name='menu_name')

In [16]:
df_melt.head(6)

   ename          dt     menu_name
0    TOM  2025-01-07           순대국
1    cho  2025-01-07           닭개장
2   hyun  2025-01-07  닭개장(특) , 꽈배기
3  JERRY  2025-01-07           닭개장
4    SEO  2025-01-07           볶음밥
5  jiwon  2025-01-07           닭개장

In [17]:
print(df_melt)

      ename          dt     menu_name
0       TOM  2025-01-07           순대국
1       cho  2025-01-07           닭개장
2      hyun  2025-01-07  닭개장(특) , 꽈배기
3     JERRY  2025-01-07           닭개장
4       SEO  2025-01-07           볶음밥
..      ...         ...           ...
165   jiwon  2025-02-05             -
166   jacob  2025-02-05             -
167  heejin  2025-02-05             -
168   lucas  2025-02-05             -
169    nuni  2025-02-05             -

[170 rows x 3 columns]

In [35]:
df_2 = df_melt
df_2 = df_2[~df_2['menu_name'].isin(['<결석>', '-', 'x'])]
df_2 = df_2.dropna()
print(df_2['ename'].value_counts())

ename
cho       15
hyun      15
heejin    15
lucas     15
jacob     15
TOM       14
JERRY     14
SEO       14
nuni      14
jiwon     12
Name: count, dtype: int64

In [37]:
df_3 = df_2.groupby('ename').size().sort_values(ascending=False)
print(df_3)

ename
heejin    15
cho       15
lucas     15
jacob     15
hyun      15
JERRY     14
SEO       14
TOM       14
nuni      14
jiwon     12
dtype: int64

In [1]:
import matplotlib.pyplot as plt

In [ ]:
import psycopg
DB_CONFIG = {
    "dbname": "",
    "user": "",
    "password":